### ISSUE TITLE
Error when passing path to javascript config file via '--config' flag

### ISSUE THREAD

**Issue by bwroblewski** [itgalaxy/webfont#480]
I receive following error when I provide path to javascript config file via `--config` flag, for example:
`webfont --config path\to\webfont\config\webfont.js`

```
Error: Could not dynamically require "path\to\webfont\config\webfont.js". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
    at commonjsRequire (C:\Users\<user>\AppData\Roaming\nvm\v12.22.1\node_modules\webfont\dist\cli.js:255:8)
    at importFresh$1 (C:\Users\<user>\AppData\Roaming\nvm\v12.22.1\node_modules\webfont\dist\cli.js:4173:9)
    at loadJs (C:\Users\<user>\AppData\Roaming\nvm\v12.22.1\node_modules\webfont\dist\cli.js:4181:18)
    at Explorer.loadFileContent (C:\Users\<user>\AppData\Roaming\nvm\v12.22.1\node_modules\webfont\dist\cli.js:4592:12)
    at C:\Users\<user>\AppData\Roaming\nvm\v12.22.1\node_modules\webfont\dist\cli.js:4614:21
```

**Comment by wszydlak** [comment]
Hi, it looks like in master branch it is resolved (probably bumping rollup version resolved this). I checked and this errors occurs no more. @jimmyandrade when can we expect some release?

**Comment by jimmyandrade** [comment]
Thanks for reporting this, and thanks @wszydlak for confirming it on `master` back in 2021.

## What we found

The stack trace points at the **old Rollup-bundled CLI** (`dist/cli.js`) and `@rollup/plugin-commonjs` blocking a dynamic `require()` of a JavaScript config file. That bundling model cannot load arbitrary `webfont.config.js` paths at runtime.

Current **webfont 12.x** ships an **ESM CLI** (`dist/cli.mjs`, built with Vite) and loads configs through **cosmiconfig**, which evaluates `.js` config files normally. We verified on `master`:

```shell
webfont "icons/*.svg" -d out --config path/to/webfont.config.js
```

This works with a relative or absolute path to `webfont.config.js` / `.webfontrc.js`.

## Release status (your “when can we expect a release?” question)

- **This specific bug** has been resolved on npm for a long time — any recent **11.x / 12.x** install should not show the Rollup `dynamicRequireTargets` error. If you still see `dist/cli.js` in the trace, upgrade: `npm install webfont@latest` (latest today: **12.0.1**).
- **New fixes** (for example template `fontName` vs `templateFontName` in #331) merge to `master` first, then ship in the **next** Release Please version after that PR merges — they are **not** on npm until that release is published.

## Regression coverage

PR (link below) adds CLI and API tests so `--config` with a `.js` file stays covered.

We are closing this issue because the underlying problem is already fixed on current releases; comment if you still reproduce it on **webfont@12.0.1** with a minimal `webfont.config.js` and we can reopen.

**Comment by jimmyandrade** [comment]
Closing: fixed on current npm releases (ESM CLI + cosmiconfig). Regression tests in the PR above.

**Comment by jimmyandrade** [comment]
Regression tests: https://github.com/itgalaxy/webfont/pull/728
