### ISSUE TITLE
CLI round parameter is passed as a string in  SVGPathData (Bug)

### ISSUE THREAD

**Issue by kdzone** [itgalaxy/webfont#569]
If run the Windows command (without config file!!!) :
`webfont %OUT_DIR%/**/*.svg --round 4`

An error occurs:
```
Error: assertNumbers arguments[0] is not a number. string == typeof 4
    at o (C:\Users\admin\AppData\Roaming\npm\node_modules\webfont\node_modules\svg-pathdata\lib\SVGPathData.cjs:15:1645)
    at Object.t.ROUND (C:\Users\admin\AppData\Roaming\npm\node_modules\webfont\node_modules\svg-pathdata\lib\SVGPathData.cjs:15:5996)
 ...
```

**Comment by jimmyandrade** [comment]
Investigating — fix in progress: https://github.com/itgalaxy/webfont/pull/ (opening now). The `--round` CLI flag was passed as a string; we are parsing it as a number. Migration notes will be in MIGRATION.md.
